# Generated by Django 4.0 on 2021-12-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kvint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(default='initial', max_length=255, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_msg',
            field=models.CharField(default='', max_length=255, verbose_name='Способ оплаты'),
        ),
    ]
